### ISSUE TITLE
window is not defined [Reference Error] 

### ISSUE THREAD

**Issue by Yasir900aslam** [infinitered/reactotron-react-js#718]
### Issue Detail
While bootstrapping reactotron-react-js with NextJS project, NextJS throws this error bellow : 

`Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
getNavigatorProperty
file:///home/yasir/Desktop/practise/aurora/aurora/node_modules/reactotron-react-js/dist/index.js (1:1307)
Object.<anonymous>
file:///home/yasir/Desktop/practise/aurora/aurora/node_modules/reactotron-react-js/dist/index.js (1:1641)
Module._compile
node:internal/modules/cjs/loader (1092:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1121:10)
Module.load
node:internal/modules/cjs/loader (972:32)
Function.Module._load
node:internal/modules/cjs/loader (813:14)
Module.require
node:internal/modules/cjs/loader (996:19)
require
node:internal/modules/cjs/helpers (92:18)
Object.reactotron-react-js
file:///home/yasir/Desktop/practise/aurora/aurora/.next/server/pages/index.js (198:18)
__webpack_require__
file:///home/yasir/Desktop/practise/aurora/aurora/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./utils/reactortron.js (2:77)
Object../utils/reactortron.js
file:///home/yasir/Desktop/practise/aurora/aurora/.next/server/pages/index.js (88:1)
__webpack_require__
file:///home/yasir/Desktop/practise/aurora/aurora/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./pages/index.js (13:76)
Object../pages/index.js
file:///home/yasir/Desktop/practise/aurora/aurora/.next/server/pages/index.js (77:1)
__webpack_require__
file:///home/yasir/Desktop/practise/aurora/aurora/.next/server/webpack-runtime.js (33:42)`

### Mitigation
I have used `typeof window ==="undefined"` but reactotron-react-js still throws an error, I think this line [https://github.com/infinitered/reactotron-react-js/blob/ac7f1e951a85326c8e717c08f0f1e11e507e993a/src/index.ts#L33](url) might be causing some problems, if window is undefined then there should be no need to createSocket, just throw a socket creation error.

### Technical Details
- NextJS version : ^10.2.3
- React version : 17.0.1
- reactotron-react-js version : ^3.3.7

**Comment by kevinvangelder** [comment]
I am also experiencing this error. According to this StackOverflow, wrapping it in a `useEffect` may solve our problem. https://stackoverflow.com/questions/55151041/window-is-not-defined-in-next-js-react-app

**Comment by jamonholmgren** [comment]
Fixed in 3.3.8 (pr #862 by @kevinvangelder )

https://github.com/infinitered/reactotron-react-js/releases/tag/v3.3.8
